### ISSUE TITLE
[방법] Jekyll 에서 글양식 기능을 사용하는 방법

### ISSUE THREAD

**Issue by Eu4ng** [Eu4ng/eu4ng.github.io#2]
### 소개

Jekyll 에서 글양식 기능을 사용하는 방법으로 본문 글양식은 포함되지 않습니다.

```yaml
---
layout: post
title: 포스트 제목
date: 2024-01-30 16:12 +0900
author: Eu4ng
categories: []
tags: []
imgae:
  path:
  alt:
---
```

### 요약

1. jekyll-compose 설치
2. 글양식 지정
3. 게시글 생성

---

### 1. jekyll-compose 설치

루트 디렉토리에 있는 `Gemfile` 에 아래 내용 추가

```rb
gem "jekyll-compose", group: [:jekyll_plugins]
```

jekyll-compose 플러그인 설치

```bash
bundle
```

### 2. 글양식 지정

루트 디렉토리에 있는 `_config.yaml` 에 아래 내용 추가

```yaml
jekyll_compose:
  default_front_matter:
    drafts:
      author: 
      categories: []
      tags: []
      imgae:
        path: 
        alt: 
    posts:
      author: 
      categories: []
      tags: []
      imgae:
        path: 
        alt: 
```

### 3. 게시글 생성

기본적으로 아래 명령어를 자주 사용합니다.

```bash
jekyll post "글 제목"
```

기타 다른 명령어 목록입니다.

```shell
draft      # 글양식이 적용된 Draft 생성 - 작성 시간 기록 없음
post       # 글양식이 적용된 Post 생성
publish    # Draft 파일을 Post 폴더로 옮긴 후 작성 시간 기록
unpublish  # Post 파일을 Draft 로 옮긴 후 작성 시간 삭제
page       # Page 생성
rename     # Draft 이름 변경
compose    # 새로운 파일 생성
```

---

## 참고

- [jekyll-compose를 사용하여 쉽게 게시글 생성하기 / 블로그](https://10kseok.github.io/posts/easy-to-make-default-mdfile-to-use-jekyll-compose/)
- [jekyll-compose / GitHub](https://github.com/jekyll/jekyll-compose)
